### ISSUE TITLE
Burkes dithering matrix might be wrong

### ISSUE THREAD

**Issue by SteveHawk** [makeworld-the-better-one/dither#10]
Hey there, love the project, but the burkes dithering matrix here appears to be wrong:

[error_diffusers.go#L97](https://github.com/makeworld-the-better-one/dither/blob/master/error_diffusers.go#L97)

> `{0, 0, 0, 8.0 / 32, 8.0 / 32},`

Which I believe should be {0, 0, 0, 8.0 / 32, **4.0** / 32}, according to [libcaca/study/3](http://caca.zoy.org/wiki/libcaca/study/3#:~:text=Judice-Ninke%20dithering%3A-,burkes%20dithering,-is%20yet%20another), and [Image Dithering: Eleven Algorithms and Source Code](https://tannerhelland.com/2012/12/28/dithering-eleven-algorithms-source-code.html#:~:text=1%0A%0A%20%20%20%20%20%20(1%2F8)-,burkes%20dithering,-Seven%20years%20after)

**Comment by makew0rld** [comment]
Thanks for bringing this up! Fixed in 1569118. Let me know if you'd like a new release.
